#!/bin/bash
# This script downloads covid data and displays it

DATA=$(curl https://api.covidtracking.com/v1/us/current.json)
POSITIVE=$(echo $DATA | jq '.[0].positive')
NEGATIVE=$(echo $Date | jq '.[0].negative')
INHOS=$(echo $DATA | jq '.[0].hospitalizedCurrently')
ICU=$(echo $DATA | jq '.[0].inIcuCurrently')
TODAY=$(date)


echo "On $TODAY, there were $POSITIVE positive COVID cases and $NEGATIVE negative COVID cases. 
Currently there are a total of $INHOS people in the hospital with $ICU in the ICU"
